# Generated by Django 4.2.11 on 2024-05-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_customer_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cart',
            field=models.TextField(default='[]'),
        ),
    ]
