# Generated by Django 4.2.11 on 2024-05-11 11:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0012_alter_coupon_deadline_alter_faq_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 11, 11, 41, 51, 630345, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='faq',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 11, 11, 41, 51, 628772, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 5, 11, 11, 41, 51, 629851, tzinfo=datetime.timezone.utc)),
        ),
    ]
