# Generated by Django 4.2.11 on 2024-05-11 11:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0013_alter_coupon_deadline_alter_faq_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='deadline',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='faq',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
