# Generated by Django 4.2.11 on 2024-05-11 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0014_alter_coupon_deadline_alter_faq_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='age',
            field=models.IntegerField(default=18),
        ),
    ]
