# Generated by Django 4.2.11 on 2024-05-13 10:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0015_customer_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='age',
        ),
        migrations.AddField(
            model_name='customer',
            name='birthdate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
