# Generated by Django 4.2.11 on 2024-05-15 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0016_remove_customer_age_customer_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
