# Generated by Django 4.2.11 on 2024-05-15 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0019_alter_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
