# Generated by Django 4.2.11 on 2024-05-16 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0022_employee_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vacancy',
        ),
    ]
