# Generated by Django 4.2.11 on 2024-05-16 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0023_delete_vacancy'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacancyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('name', models.TextField()),
                ('salary', models.FloatField()),
                ('info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pizza.vacancyinfo')),
            ],
        ),
    ]
