# Generated by Django 4.2.11 on 2024-05-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0024_vacancyinfo_vacancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='vacancy',
            field=models.ManyToManyField(blank=True, to='pizza.vacancy'),
        ),
    ]
